
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zhiyo
 */
public class studentHomePageGUI extends javax.swing.JFrame {
    private final String studentID;

    /**
     * Creates new form studentHomePageGUI
     * @param userID
     * @param username
     * @param userTypes
     */
    public studentHomePageGUI(String userID, String username, String userTypes) {
        initComponents();
        this.studentID = userID;
        
        setTitle("APU Psychology Consultation System ---" + userID + " (" + userTypes + ")");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int logOut = JOptionPane.showConfirmDialog(null, "Log Out?", "Log Out", JOptionPane.YES_NO_OPTION);
                if (logOut == JOptionPane.YES_OPTION) {
                    Login login = new Login();
                    login.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Cancelled Log Out. Go back to Home Page......", "Log Out Cancellation", JOptionPane.OK_OPTION);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AvailableSlot = new javax.swing.JButton();
        UpcomingAPMT = new javax.swing.JButton();
        ConsultationFeedback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        ViewLecturerFeedback = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AvailableSlot.setBackground(new java.awt.Color(255, 0, 51));
        AvailableSlot.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        AvailableSlot.setForeground(new java.awt.Color(255, 255, 255));
        AvailableSlot.setText("Make consultation");
        AvailableSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailableSlotActionPerformed(evt);
            }
        });
        getContentPane().add(AvailableSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 390, 51));

        UpcomingAPMT.setText("Upcoming appointment");
        UpcomingAPMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpcomingAPMTActionPerformed(evt);
            }
        });
        getContentPane().add(UpcomingAPMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 188, 51));

        ConsultationFeedback.setText("Consultation Feedback");
        ConsultationFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultationFeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultationFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 188, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("APU Psychology System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 23, 440, -1));

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        ViewLecturerFeedback.setText("View Lecturer Feedback");
        ViewLecturerFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLecturerFeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(ViewLecturerFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 390, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JavaStudentBackground.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpcomingAPMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpcomingAPMTActionPerformed
        studentViewAppointment ViewAppointment = new studentViewAppointment(this.studentID);
        ViewAppointment.setVisible(true);
    }//GEN-LAST:event_UpcomingAPMTActionPerformed

    private void AvailableSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailableSlotActionPerformed
        ViewConsultationSlot ViewSlot = new ViewConsultationSlot(this.studentID);
        ViewSlot.setVisible(true);
        
    }//GEN-LAST:event_AvailableSlotActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        int logOut = JOptionPane.showConfirmDialog(null, "Log Out?", "Log Out", JOptionPane.YES_NO_OPTION);
        
        if (logOut == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true); 
            dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, "Cancelled Log Out. Go back to Home Page......", "Log Out Cancellation", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void ConsultationFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultationFeedbackActionPerformed
        // TODO add your handling code here:
        studentFeedback provideFeedback = new studentFeedback(this.studentID);
        provideFeedback.setVisible(true);
    }//GEN-LAST:event_ConsultationFeedbackActionPerformed

    private void ViewLecturerFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLecturerFeedbackActionPerformed
      studentViewLecturerFeedback viewFeedback = new studentViewLecturerFeedback(this.studentID);
      viewFeedback.setVisible(true);
    }//GEN-LAST:event_ViewLecturerFeedbackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AvailableSlot;
    private javax.swing.JButton ConsultationFeedback;
    private javax.swing.JButton UpcomingAPMT;
    private javax.swing.JButton ViewLecturerFeedback;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    // End of variables declaration//GEN-END:variables
}
